=== svibhav03/sppu_WTL/31268_assign3_xml/employees.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, position, department, salary)>
<!ATTLIST employee id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== svibhav03/sppu_WTL/31268_assign3_xml/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<?xml-stylesheet type="text/xsl" href="employees.xsl"?>

<employees>
    <employee id="1">
        <name>Vibhav Sahasrabudhe</name>
        <position>Software Engineer</position>
        <department>IT</department>
        <salary>80000</salary>
    </employee>
    
    <employee id="2">
        <name>Amit Sharma</name>
        <position>Database Administrator</position>
        <department>IT</department>
        <salary>85000</salary>
    </employee>

    <employee id="3">
        <name>Priya Patel</name>
        <position>Network Engineer</position>
        <department>IT</department>
        <salary>78000</salary>
    </employee>

    <employee id="4">
        <name>Raj Singh</name>
        <position>Systems Analyst</position>
        <department>IT</department>
        <salary>82000</salary>
    </employee>

    <employee id="5">
        <name>Ananya Joshi</name>
        <position>Web Developer</position>
        <department>IT</department>
        <salary>75000</salary>
    </employee>

    <employee id="6">
        <name>Sandeep Verma</name>
        <position>Security Analyst</position>
        <department>IT</department>
        <salary>90000</salary>
    </employee>

    <employee id="7">
        <name>Neha Kapoor</name>
        <position>Data Scientist</position>
        <department>Research and Development</department>
        <salary>95000</salary>
    </employee>

    <employee id="8">
        <name>Vikram Mehra</name>
        <position>Project Manager</position>
        <department>Management</department>
        <salary>100000</salary>
    </employee>

    <employee id="9">
        <name>Pooja Rawat</name>
        <position>Quality Assurance Engineer</position>
        <department>IT</department>
        <salary>82000</salary>
    </employee>

    <employee id="10">
        <name>Rahul Gupta</name>
        <position>UX/UI Designer</position>
        <department>Design</department>
        <salary>78000</salary>
    </employee>

    
</employees>
